/*
 * Read one calibration take and settle everything it can.
 *
 *   node benchcal.js <take.wav> [disk image]
 *
 * The take is the 14 notes of AkaiCalibration.mid played through CALIB. Clips are
 * identified by their position in the run and nothing else, so the running order in
 * benchplan.js has to be the one that was played.
 *
 * Every measurement divides out the NOISE sample, which is generated by this project and
 * sits bit-exact in the disk image - so the source spectrum, the level of each clip and
 * anything the recording chain added all cancel, and only the sampler's own shaping is
 * left.
 */
var fs = require('fs');
var cal = require('./vcfcal.js');
var plan = require('./benchplan.js');
var Akai = require('./akai.js');

var file = process.argv[2];
var image = process.argv[3] || 'DSKA0000-bench.hfe';

if (!file) {
  console.log('usage: node benchcal.js <take.wav> [disk image]');
  process.exit(1);
}

// ---------------------------------------------------------------- the source

var disk = Akai.load('x', new Uint8Array(fs.readFileSync(image)));
var smp = null;
disk.entries.forEach(function (e) { if (e.type === 'S' && e.name.trim() === 'NOISE') smp = e; });
if (!smp) { console.log('no NOISE sample in ' + image); process.exit(1); }

var words = disk.sampleWords12(smp);
var source = new Float64Array(words.length);
for (var i = 0; i < words.length; i++) source[i] = words[i] / 2048;
var srcSpec = cal.spectrum(source, smp.sampleRate, cal.BANDS);

// ------------------------------------------------------------------ the take

var w = cal.readWav(file);
var wanted = plan.clips();
// the plan leaves 1.5 s between notes, so half of that is safely a real gap
var found = cal.splitClips(w.samples, w.rate, wanted.length,
                           { minGapSeconds: plan.TIMING.gap * 0.5 });

/**
 * Match what was found against where the plan says it should be.
 *
 * Counting clips was fine while every note sounded. It is not: the run asks for velocity
 * 20 at full velocity->loudness depth, which on the machine is quieter than the noise
 * floor, so the note is simply not there. Refusing the whole take over one absent note
 * threw away twenty-one good measurements.
 *
 * The timeline is known exactly - makemidi.js writes it from this same plan - so a clip
 * can be placed by when it happened. The one unknown is when recording started, and that
 * is a single constant for the whole take: try every offset that would line some found
 * clip up with some expected one, and keep whichever explains the most.
 */
function expectedTimes() {
  var t = plan.TIMING, at = t.lead, out = [];
  wanted.forEach(function (c, i) {
    if (i > 0 && c.first) at += t.sectionGap - t.gap;
    out.push(at);
    at += t.hold + t.gap;
  });
  return out;
}

function align() {
  var want = expectedTimes();
  var starts = found.clips.map(function (c) { return c.seconds[0]; });
  var tol = plan.TIMING.gap * 0.6;          // comfortably less than the gap between notes
  var best = { score: -1, map: null, offset: 0 };

  starts.forEach(function (s0) {
    want.forEach(function (w0) {
      var off = s0 - w0, used = {}, map = [], score = 0;

      want.forEach(function (at) {
        var pick = -1, near = tol;
        starts.forEach(function (s, j) {
          if (used[j]) return;
          var d = Math.abs(s - (at + off));
          if (d < near) { near = d; pick = j; }
        });
        if (pick >= 0) { used[pick] = true; score++; }
        map.push(pick);
      });

      if (score > best.score) { best = { score: score, map: map, offset: off }; }
    });
  });
  return best;
}

var placed = align();
var slot = placed.map;                      // plan index -> found index, or -1
var times = expectedTimes();

if (placed.score < 2) {
  console.log('only ' + placed.score + ' of ' + wanted.length + ' clips could be placed ' +
              'on the timeline the plan writes. The take must be the whole run, in order.');
  process.exit(1);
}

console.log('');
console.log('take: ' + (w.samples.length / w.rate).toFixed(1) + 's at ' + w.rate + ' Hz, ' +
            placed.score + ' of ' + wanted.length + ' clips, peak ' +
            found.peakDb.toFixed(1) + ' dBFS, floor ' + found.floorDb.toFixed(0) +
            ' dB below that');

// A note that never sounded is worth naming: it is a hole in the measurement, and the
// level where it should have been says whether it was too quiet to record or never played.
wanted.forEach(function (c, i) {
  if (slot[i] >= 0) return;

  var at = times[i] + placed.offset;
  var a = Math.max(0, Math.round((at + 0.3) * w.rate));
  var b = Math.min(w.samples.length, Math.round((at + plan.TIMING.hold - 0.3) * w.rate));
  var sum = 0;
  for (var j = a; j < b; j++) sum += w.samples[j] * w.samples[j];
  var db = 10 * Math.log10(Math.max(sum / Math.max(b - a, 1), 1e-30));

  console.log('  no clip for ' + c.section + ' / ' + c.label + ' (note ' + c.note +
              ', velocity ' + c.velocity + ') at ' + at.toFixed(1) + 's  -  that stretch ' +
              'measures ' + db.toFixed(1) + ' dBFS');
});

/**
 * The -3 dB corner of a stretch of audio against the known source.
 *
 * Which bands count as passband depends on where the corner lands, so it is found once
 * against the very bottom of the spectrum and then again levelled well below that - a
 * fixed window levels on the roll-off whenever the corner is low, and reads high.
 */
function corner(samples) {
  var spec = cal.spectrum(samples, w.rate, cal.BANDS);

  function find(topHz) {
    var ref = 0, n = 0;
    for (var j = 0; j < cal.BANDS.length; j++)
      if (cal.BANDS[j] < topHz) { ref += spec[j].db - srcSpec[j].db; n++; }
    if (n < 3) { ref = 0; for (var j = 0; j < 3; j++) ref += spec[j].db - srcSpec[j].db; n = 3; }
    ref /= n;

    for (var j = 1; j < cal.BANDS.length; j++) {
      var a = (spec[j - 1].db - srcSpec[j - 1].db) - ref;
      var b = (spec[j].db - srcSpec[j].db) - ref;
      if (b <= -3 && a > -3) {
        var t = (a + 3) / (a - b);
        return cal.BANDS[j - 1] * Math.pow(cal.BANDS[j] / cal.BANDS[j - 1], t);
      }
    }
    return null;
  }

  var rough = find(cal.BANDS[3]);
  return rough ? find(Math.max(rough / 3, cal.BANDS[3])) : null;
}

/** The audio of plan clip `i`, or null where the note never sounded. */
function clipAudio(i) {
  if (slot[i] < 0) return null;
  var c = found.clips[slot[i]];
  return w.samples.subarray(c.from, c.to);
}

/*
 * When each note actually began.
 *
 * A clip's edges are found by threshold, which trims the quiet start of a note off the
 * front - fine for a spectrum, wrong for anything measuring time, because it silently
 * moves t=0 to wherever the note became loud enough to notice. On a slow attack that is
 * most of the attack. The envelope sections therefore count from the note-on the plan
 * scheduled, not from the trimmed edge.
 *
 * The offset between the two is when recording started, taken as the median across every
 * matched clip so that one oddly-trimmed note cannot move it.
 */
/**
 * When the run began, from the notes themselves.
 *
 * Not from the clip edges: the splitter reports a start about 0.3 s late - it is looking
 * for a run of sound rather than an edge, and that is fine for a spectrum and useless for
 * a time. Measured against a rendering whose notes are known to begin exactly on the
 * second, it put every one of them at 1.299 s.
 *
 * So the onset is found here instead: step 10 ms frames forward from well before the note
 * and take the first that rises clear of the silence in front of it. Then the median
 * across every matched clip, which is robust to the one note with a slow attack.
 */
function onsetNear(when) {
  var frame = Math.max(64, Math.round(w.rate * 0.01));
  var from = Math.max(0, Math.round((when - 1.0) * w.rate));
  var to = Math.min(w.samples.length, Math.round((when + 1.0) * w.rate));

  var levels = [];
  for (var at = from; at + frame <= to; at += frame) {
    var sum = 0;
    for (var j = 0; j < frame; j++) { var v = w.samples[at + j]; sum += v * v; }
    levels.push(Math.sqrt(sum / frame));
  }
  if (levels.length < 8) return null;

  // the quiet before the note, taken low enough down the order to ignore the note itself
  var sorted = levels.slice().sort(function (x, y) { return x - y; });
  var quiet = sorted[Math.floor(sorted.length * 0.2)];
  var loud = sorted[sorted.length - 1];
  if (loud <= quiet * 2) return null;                 // no edge here to find

  var bar = Math.max(quiet * 3, loud * 0.02);         // clear of the noise, low on the note
  for (var i = 0; i < levels.length; i++)
    if (levels[i] > bar) return (from + i * frame) / w.rate;
  return null;
}

var offsets = [];
wanted.forEach(function (c, i) {
  if (slot[i] < 0) return;
  var on = onsetNear(times[i] + placed.offset);
  if (on !== null) offsets.push(on - times[i]);
});
offsets.sort(function (x, y) { return x - y; });
var startedAt = offsets.length ? offsets[Math.floor(offsets.length / 2)] : placed.offset;

console.log('      notes begin ' + startedAt.toFixed(2) + 's from where the plan puts them');

/** A note from the instant it was played, for the measurements that are about time. */
function noteAudio(i) {
  if (slot[i] < 0) return null;
  var from = Math.max(0, Math.round((times[i] + startedAt) * w.rate));
  var to = Math.min(w.samples.length, Math.round((times[i] + startedAt + plan.TIMING.hold) * w.rate));
  return w.samples.subarray(from, to);
}

/**
 * Drop the points where the filter has run out of travel.
 *
 * The measured ladder saturates at both ends - stored 0 and 20 give an identical curve,
 * and so do 80 and 99 - because the cutoff cannot go below its floor or above the
 * reconstruction limit of 0.4 x the sample rate. Fitting through those flat ends drags
 * the curve badly: it is what turned a real 0.37 into a reported MAX_RATIO of 0.54.
 * Two neighbours within a tenth of an octave of each other are both at a stop.
 */
function unsaturated(points) {
  if (points.length < 3) return { keep: points, floor: null, ceiling: null };

  var flat = points.map(function (p, i) {
    var before = i > 0 ? Math.abs(Math.log2(p.y / points[i - 1].y)) : 9;
    var after = i < points.length - 1 ? Math.abs(Math.log2(points[i + 1].y / p.y)) : 9;
    return Math.min(before, after) < 0.1;
  });

  var keep = points.filter(function (p, i) { return !flat[i]; });

  // Which stop a flat point is against has to be decided by where it sits in the whole
  // range, not against the last point: comparing with the last put 16310 on the low side
  // of 16311 and reported a 311 Hz floor as 5644.
  var all = points.map(function (p) { return p.y; });
  var middle = Math.sqrt(Math.min.apply(null, all) * Math.max.apply(null, all));

  var low = points.filter(function (p, i) { return flat[i] && p.y < middle; });
  var high = points.filter(function (p, i) { return flat[i] && p.y >= middle; });

  return {
    keep: keep,
    floor: low.length ? low.reduce(function (a, b) { return a + b.y; }, 0) / low.length : null,
    ceiling: high.length ? high.reduce(function (a, b) { return a + b.y; }, 0) / high.length : null
  };
}

/** Least squares of log2(y) against x. */
function fitLog2(points) {
  var sx = 0, sy = 0, sxx = 0, sxy = 0, n = points.length;
  points.forEach(function (p) {
    var y = Math.log2(p.y);
    sx += p.x; sy += y; sxx += p.x * p.x; sxy += p.x * y;
  });
  var slope = (n * sxy - sx * sy) / (n * sxx - sx * sx);
  var intercept = (sy - slope * sx) / n;

  var worst = 0;
  points.forEach(function (p) {
    worst = Math.max(worst, Math.abs(Math.log2(p.y) - (intercept + slope * p.x)));
  });
  return { slope: slope, intercept: intercept, worstOctaves: worst };
}

// group the clips by the section that asked for them
var sections = {};
wanted.forEach(function (c, i) {
  var sec = sections[c.analysis] || (sections[c.analysis] = { info: c, at: [], missing: [] });
  (slot[i] >= 0 ? sec.at : sec.missing).push(i);
});

/** A section is worth reporting only if something of it was actually recorded. */
function has(name) {
  var sec = sections[name];
  if (!sec || !sec.at.length) return false;

  if (sec.missing.length)
    sec.note = '   (' + sec.missing.length + ' of its ' +
               (sec.at.length + sec.missing.length) + ' clips did not sound: ' +
               sec.missing.map(function (i) { return wanted[i].label; }).join(', ') + ')';
  return true;
}

var result = {};

// --------------------------------------------------------- 1. the filter ladder
if (has('ladder')) {
  console.log('');
  console.log('FILTER LADDER  -  where the stored 0..99 cutoff actually sits');
  console.log('   stored    -3 dB corner');

  var pts = [];
  sections.ladder.at.forEach(function (i) {
    var c = corner(clipAudio(i));
    var stored = wanted[i].filter;
    console.log('     ' + String(stored).padStart(3) + '      ' +
                (c ? c.toFixed(0).padStart(6) + ' Hz' : '  not found'));
    if (c) pts.push({ x: stored / 99, y: c });
  });

  var u = unsaturated(pts);

  if (u.floor !== null) {
    console.log('');
    console.log('   the cutoff will not go below ' + u.floor.toFixed(0) +
                ' Hz however far the control is turned down');
    result.FLOOR_HZ = u.floor;
  }
  if (u.ceiling !== null) {
    console.log('   and not above ' + u.ceiling.toFixed(0) + ' Hz  -  ' +
                (u.ceiling / smp.sampleRate).toFixed(3) + ' x the sample rate' +
                '  (0.4 would be ' + (0.4 * smp.sampleRate).toFixed(0) + ' Hz)');
    result.MAX_RATIO = u.ceiling / smp.sampleRate;
  }

  if (u.keep.length >= 2) {
    var f = fitLog2(u.keep);
    var perUnit = f.slope / 99;

    console.log('');
    console.log('   between the stops it moves ' + perUnit.toFixed(4) +
                ' octaves per stored unit - ' + f.slope.toFixed(1) + ' octaves over the range');
    console.log('   which puts a notional 0 at ' + Math.pow(2, f.intercept).toFixed(0) +
                ' Hz and 99 at ' + (Math.pow(2, f.intercept + f.slope) / 1000).toFixed(1) + ' kHz,');
    console.log('   both outside what the hardware will actually do');
    console.log('   fitted from ' + u.keep.length + ' unsaturated points' +
                (u.keep.length < 3 ? '  -  too few to be sure of the slope' : ''));

    result.MIN_HZ = Math.pow(2, f.intercept);
    result.ladderPoints = u.keep.length;
  } else {
    console.log('');
    console.log('   only ' + u.keep.length + ' point is off the end stops, so the slope');
    console.log('   cannot be fitted. Record a ladder with finer steps between 20 and 80.');
  }
}

// ------------------------------------------------------------ 2. key tracking
if (has('keytrack')) {
  console.log('');
  console.log('KEY TRACKING  -  how far the keyboard moves the cutoff at keyToFilter 50');
  console.log('   note     -3 dB corner');

  var pts2 = [];
  sections.keytrack.at.forEach(function (i) {
    var c = corner(clipAudio(i));
    console.log('    ' + String(wanted[i].note).padStart(3) + '      ' +
                (c ? c.toFixed(0).padStart(6) + ' Hz' : '  not found'));
    if (c) pts2.push({ x: (wanted[i].note - 60) / 12, y: c });
  });

  if (pts2.length >= 2) {
    var f2 = fitLog2(pts2);
    result.trackAt50 = f2.slope;
    console.log('');
    console.log('   ' + f2.slope.toFixed(3) + ' octaves of cutoff per octave of keyboard');
    console.log('   worst departure from a straight line: ' + f2.worstOctaves.toFixed(2) + ' octaves');
    if (f2.slope > 0.05) result.KEY_FULL = 50 / f2.slope;
  }
}

// -------------------------------------------------------- 3. the filter envelope
//
// Two clips, at half amount and full. The cutoff starts high and falls back to the base
// over the decay, so the top of the trace gives the depth and the shape of the fall
// gives the time. Windows of a quarter second: shorter than that and the spectrum has
// too little resolution to place a corner near 1 kHz, which is what made the first
// attempt return noise.
if (has('filterenv')) {
  console.log('');
  console.log('FILTER ENVELOPE  -  the cutoff falling back to its base');

  var depths = [];

  sections.filterenv.at.forEach(function (idx) {
    var audio = noteAudio(idx);
    var label = wanted[idx].label;
    var win = Math.round(w.rate * 0.25);
    var hop = Math.round(win / 2);
    var trace = [];

    for (var o = 0; o + win <= audio.length; o += hop) {
      var c = corner(audio.subarray(o, o + win));
      if (c) trace.push({ t: (o + win / 2) / w.rate, hz: c });
    }

    // A quarter-second window is short enough that the corner finder sometimes fails,
    // and it fails by reporting a frequency near the bottom of the band list rather than
    // by returning nothing: 312 Hz and 169 Hz turned up between neighbours at 8578 and
    // 5844. Left in, they drag the settled value and put "halfway down" wherever the
    // first bad window happened to be.
    //
    // The sweep only ever falls, so a point with a LATER point well above it cannot be
    // right. That is enough to pick the failures out without any threshold on the value
    // itself, which matters because a genuine reading down at the 311 Hz floor has to
    // survive.
    var kept = [], dropped = 0;
    for (var k = 0; k < trace.length; k++) {
      var above = false;
      for (var m = k + 1; m < trace.length; m++)
        if (trace[m].hz > trace[k].hz * 1.19) { above = true; break; }   // 0.25 octaves
      if (above) dropped++; else kept.push(trace[k]);
    }
    if (dropped) console.log('   (' + dropped + ' windows could not be read and were dropped)');
    trace = kept;

    console.log('');
    console.log('   ' + label + ':');

    if (trace.length < 4) {
      console.log('      could not follow it - only ' + trace.length + ' windows measured');
      return;
    }

    trace.forEach(function (pt, i) {
      if (i % 2 && i !== trace.length - 1) return;
      console.log('      ' + pt.t.toFixed(2).padStart(5) + 's  ' + pt.hz.toFixed(0).padStart(6) + ' Hz');
    });

    // Where the sweep came to rest, as the median of its last third - not the final
    // window, which catches the note running out and can read anything. Taking the last
    // point made a sweep that plainly settled at 1149 Hz measure as though it reached 167.
    var tail = trace.slice(Math.floor(trace.length * 0.66)).map(function (q) { return q.hz; });
    tail.sort(function (a, b) { return a - b; });

    var top = trace[0].hz;
    var settled = tail[Math.floor(tail.length / 2)];
    var octaves = Math.log2(top / settled);

    // the sweep should end at the keygroup's own base cutoff; if it does not, the
    // clip ran out before the envelope did
    console.log('      starts at ' + top.toFixed(0) + ' Hz, ends at ' + settled.toFixed(0) +
                ' Hz  -  ' + octaves.toFixed(2) + ' octaves');

    // how long to fall halfway, in octaves
    var halfway = top / Math.pow(2, octaves / 2);
    var halfAt = null;
    for (var i = 0; i < trace.length; i++)
      if (halfAt === null && trace[i].hz <= halfway) halfAt = trace[i].t;

    console.log('      halfway down at ' + (halfAt === null ? '?' : halfAt.toFixed(2) + 's') +
                '   (stored decay 80)');

    var amount = label.indexOf('25') >= 0 ? 25 : 50;
    if (octaves > 0.3) depths.push({ amount: amount, octaves: octaves, halfAt: halfAt });
  });

  if (depths.length) {
    console.log('');
    depths.forEach(function (dpt) {
      console.log('   amount ' + dpt.amount + ' gives ' + dpt.octaves.toFixed(2) +
                  ' octaves  ->  ' + (dpt.octaves * 50 / dpt.amount).toFixed(1) +
                  ' octaves at full amount');
    });

    if (depths.length >= 2) {
      var ratio = (depths[1].octaves / depths[1].amount) / (depths[0].octaves / depths[0].amount);
      console.log('   the two agree to within ' + Math.abs((ratio - 1) * 100).toFixed(0) +
                  '%, so the depth is ' + (Math.abs(ratio - 1) < 0.2 ? 'linear in the amount' :
                  'NOT linear in the amount - or the deeper one hit a stop'));
    }

    // take the shallower sweep: less likely to have run into the ceiling
    var best = depths[0];
    result.ENV_OCTAVES = best.octaves * 50 / best.amount;
    result.envHalfAt80 = best.halfAt;
  }
}

// ----------------------------------------------------- 4. the amplitude envelope
if (has('vcaenv')) {
  console.log('');
  console.log('AMPLITUDE ENVELOPE  -  the level decaying to nothing');

  var a4 = noteAudio(sections.vcaenv.at[0]);
  var win4 = Math.round(w.rate * 0.05);
  var env = [];

  for (var o = 0; o + win4 <= a4.length; o += win4) {
    var s = 0;
    for (var i = 0; i < win4; i++) s += a4[o + i] * a4[o + i];
    env.push({ t: (o + win4 / 2) / w.rate, db: 10 * Math.log10(Math.max(s / win4, 1e-30)) });
  }

  var peak4 = Math.max.apply(null, env.map(function (e) { return e.db; }));
  var halfAt = null, downAt = null;

  env.forEach(function (e) {
    if (halfAt === null && e.db <= peak4 - 6) halfAt = e.t;
    if (downAt === null && e.db <= peak4 - 40) downAt = e.t;
  });

  console.log('   -6 dB at ' + (halfAt === null ? '?' : halfAt.toFixed(2) + 's') +
              ',  -40 dB at ' + (downAt === null ? 'not reached' : downAt.toFixed(2) + 's') +
              '   (stored decay 80)');

  console.log('');
  console.log('   trace:');
  env.forEach(function (e, i) {
    if (i % 4) return;
    console.log('     ' + e.t.toFixed(2).padStart(5) + 's  ' + (e.db - peak4).toFixed(1).padStart(6) + ' dB');
  });

  result.vcaMinus6At80 = halfAt;
}

// ------------------------------------------------------- 5. velocity to filter
if (has('velocity')) {
  console.log('');
  console.log('VELOCITY TO FILTER  -  at velToFilter 99');
  console.log('   velocity   -3 dB corner');

  var pts5 = [];
  sections.velocity.at.forEach(function (i) {
    var c = corner(clipAudio(i));
    console.log('     ' + String(wanted[i].velocity).padStart(3) + '       ' +
                (c ? c.toFixed(0).padStart(6) + ' Hz' : '  not found'));
    if (c) pts5.push({ x: wanted[i].velocity / 127, y: c });
  });

  var u5 = unsaturated(pts5);
  if (u5.floor !== null)
    console.log('   (the softest note is against the ' + u5.floor.toFixed(0) +
                ' Hz floor, so it says nothing about the depth)');

  if (u5.keep.length >= 2) {
    var f5 = fitLog2(u5.keep);
    result.VEL_OCTAVES = f5.slope;
    console.log('');
    console.log('   ' + f5.slope.toFixed(1) + ' octaves from silent to full velocity, from ' +
                u5.keep.length + ' usable points');
  } else if (pts5.length >= 2) {
    var f5b = fitLog2(pts5);
    console.log('');
    console.log('   ' + f5b.slope.toFixed(1) + ' octaves across the velocity range, but with');
    console.log('   points against an end stop - treat as a lower bound');
    result.VEL_OCTAVES = f5b.slope;
  }
}

// ------------------------------------------------------------- 6. the levels
//
// These need only the loudness of each clip, which makes them the cheapest measurements
// in the run and also the most fragile: they compare one clip against another, so they
// are only meaningful if the recording gain did not move. Everything else here divides
// the source out and is immune to that.
function steadyDb(i) {
  var a = clipAudio(i);
  var from = Math.floor(a.length * 0.25);          // past the attack, before any release
  var to = Math.floor(a.length * 0.75);
  var sum = 0;
  for (var j = from; j < to; j++) sum += a[j] * a[j];
  return 10 * Math.log10(Math.max(sum / (to - from), 1e-30));
}

if (has('levels')) {
  console.log('');
  console.log('LEVELS  -  read against the reference clip');

  var ref = steadyDb(sections.levels.at[0]);
  console.log('   reference                 ' + ref.toFixed(1) + ' dBFS');

  sections.levels.at.slice(1).forEach(function (i) {
    var d = steadyDb(i) - ref;
    var label = wanted[i].label;
    console.log('   ' + label.padEnd(22) + '  ' + (d >= 0 ? '+' : '') + d.toFixed(1) + ' dB');

    if (label.indexOf('sustain') >= 0) {
      result.sustain50Db = d;
      console.log('      as a plain amplitude fraction 50/99 would be ' +
                  (20 * Math.log10(50 / 99)).toFixed(1) + ' dB');
      console.log('      as a straight -dB count it would be nearer ' + d.toFixed(0) + ' dB');
    }
    if (label.indexOf('loudness') >= 0) {
      result.loudness20Db = d;
      console.log('      so one unit of zone loudness is about ' + (d / 20).toFixed(2) + ' dB');
    }
  });
}

// ------------------------------------------------- 7. velocity to loudness
if (has('velloud')) {
  console.log('');
  console.log('VELOCITY TO LOUDNESS  -  at velToLoudness 99');
  console.log('   velocity     level');

  var loud = [];
  sections.velloud.at.forEach(function (i) {
    var db = steadyDb(i);
    loud.push({ v: wanted[i].velocity, db: db });
    console.log('     ' + String(wanted[i].velocity).padStart(3) + '      ' + db.toFixed(1) + ' dBFS');
  });

  if (loud.length >= 2) {
    var top = loud[loud.length - 1];
    console.log('');
    loud.forEach(function (l) {
      if (l === top) return;
      console.log('   velocity ' + l.v + ' is ' + (l.db - top.db).toFixed(1) +
                  ' dB below velocity ' + top.v);
    });

    // a straight proportional law would put velocity v at 20log10(v/127) dB
    var predicted = loud.map(function (l) {
      return (20 * Math.log10(l.v / top.v)).toFixed(1);
    }).join(', ');
    console.log('   a simple proportional law would give ' + predicted + ' dB');
    result.velLoud = loud;
  }
}

// -------------------------------------------------------- 8. the attack time
if (has('attack')) {
  console.log('');
  console.log('ATTACK  -  how long a stored 70 takes to reach full level');

  var a8 = noteAudio(sections.attack.at[0]);
  var win8 = Math.round(w.rate * 0.02);
  var env8 = [];

  for (var o = 0; o + win8 <= a8.length; o += win8) {
    var sum = 0;
    for (var j = 0; j < win8; j++) sum += a8[o + j] * a8[o + j];
    env8.push({ t: (o + win8 / 2) / w.rate, db: 10 * Math.log10(Math.max(sum / win8, 1e-30)) });
  }

  var peak8 = Math.max.apply(null, env8.map(function (e) { return e.db; }));
  var atDb = function (target) {
    for (var i = 0; i < env8.length; i++) if (env8[i].db >= peak8 + target) return env8[i].t;
    return null;
  };

  var t10 = atDb(-20), t50 = atDb(-6), t90 = atDb(-1);
  console.log('   -20 dB at ' + (t10 === null ? '?' : t10.toFixed(2) + 's') +
              ',  -6 dB at ' + (t50 === null ? '?' : t50.toFixed(2) + 's') +
              ',  full at ' + (t90 === null ? '?' : t90.toFixed(2) + 's'));

  console.log('');
  console.log('   trace:');
  env8.forEach(function (e, i) {
    if (i % 5 || e.t > 2.2) return;
    console.log('     ' + e.t.toFixed(2).padStart(5) + 's  ' + (e.db - peak8).toFixed(1).padStart(6) + ' dB');
  });

  result.attackAt70 = t90;
}

// ----------------------------------------------------------------- the answer
console.log('');
console.log('----------------------------------------------------------------');
console.log('paste into audio.js:');
console.log('');
console.log('  var CAL = {');
console.log('    MAX_RATIO: ' + (result.MAX_HZ ? (result.MAX_HZ / smp.sampleRate).toFixed(3) : '0.4') +
            ',      // ' + (result.MAX_HZ ? 'measured' : 'unchanged'));
console.log('    MIN_HZ: ' + (result.MIN_HZ ? Math.round(result.MIN_HZ) : 100) +
            ',          // ' + (result.MIN_HZ ? 'measured' : 'still assumed'));
console.log('    ENV_OCTAVES: ' + (result.ENV_OCTAVES ? result.ENV_OCTAVES.toFixed(1) : 4) +
            ',     // ' + (result.ENV_OCTAVES ? 'measured' : 'still assumed'));
console.log('    VEL_OCTAVES: ' + (result.VEL_OCTAVES ? result.VEL_OCTAVES.toFixed(1) : 2) +
            ',     // ' + (result.VEL_OCTAVES ? 'measured' : 'still assumed'));
console.log('    KEY_FULL: ' + (result.KEY_FULL ? Math.round(result.KEY_FULL) : 99) +
            ',        // ' + (result.KEY_FULL ? 'measured' : 'still assumed'));
console.log('    ENV_MIN_MS: 1,        // still assumed');
console.log('    ENV_MAX_MS: ' + (result.envDecayAt80
            ? Math.round(result.envDecayAt80 * 1000 / Math.pow(10, 4 * 80 / 99) * 1000) : 10000) +
            '     // ' + (result.envDecayAt80 ? 'from the decay at 80' : 'still assumed'));
console.log('  };');
