/*
 * The seventh run: velocity to attack, and velocity to release.
 *
 *   node envdisk.js  build ENVCAL7           --plan envplan7.js
 *   node envmidi.js  AkaiEnvCalibration7.mid --plan envplan7.js
 *   node envcal.js   take.wav ENVCAL7.img    --plan envplan7.js
 *
 * Bytes 9 and 10 of a keygroup. Read off every disk since the format was worked out, carried
 * as far as the patch in one engine and not even that far in the other two, and modelled by
 * none of them. A keygroup that sets either currently plays with no velocity response on that
 * stage at all.
 *
 * THIS WAS NEARLY NOT WORTH DOING, AND THE EVIDENCE FOR THAT WAS WRONG
 *
 * The bundled sound library leaves both at zero in all 181 of its keygroups, which looked
 * like an answer: nothing to calibrate against and nothing playing wrongly. But that library
 * is generated by this repository, so all it says is what this repository writes. The 101
 * real Akai disks say something else entirely:
 *
 *     vel -> attack    164 keygroups of 1908, values 8 to 99,
 *                      clustered at 30, 35, 75 and 83
 *     vel -> release    20 keygroups, and 19 of those at -50
 *
 * So 164 keygroups across the library are missing a velocity response they were written with.
 * The settings below are chosen from what those programmes actually use rather than from a
 * tidy ladder - 30, 75 and 99 for the attack because that is where the library sits, and -50
 * for the release because nineteen of the twenty are there.
 *
 * WHAT HAS TO BE ESTABLISHED
 *
 *   DIRECTION   Does a harder strike make the attack shorter or longer? Nobody has said, and
 *               guessing it wrong inverts the response of 164 keygroups.
 *   DEPTH       How much, at a given byte, and does the byte scale linearly? Every other
 *               velocity depth in the model assumes byte/99 and none of those was measured
 *               either.
 *   PIVOT       Velocity to FILTER pivots at 65 rather than at nothing - a soft strike goes
 *               DOWN where a hard one goes up. If the attack does the same, a model built
 *               around zero is wrong at both ends.
 *   THE SIGN    Release is a signed byte and the library uses -50 almost exclusively. What
 *               the sign means is the whole question for that one.
 */

var FLAG_CONSTANT_PITCH = 0x01, FLAG_DESYNC = 0x04;

/// Looped, so a long attack is not cut short by the sample running out.
var LOOPING = true;

/*
 * Nothing but the stage under test may respond to velocity.
 *
 * Byte 7 and byte 11 are zero throughout, so the filter and the loudness do not move with the
 * strike - otherwise a velocity sweep would change the brightness and the level of every clip
 * as it went, and the ramp this measures is read against the clip's own plateau.
 */
var BASE = {
  3: 0, 4: 0, 5: 99, 6: 0,
  7: 0, 8: 0, 9: 0, 10: 0, 11: 0,
  15: 0, 16: 0, 17: 0,
  18: FLAG_CONSTANT_PITCH | FLAG_DESYNC,
  21: 0, 22: 0,
  23: 0,
  34: 0, 35: 99, 36: 99, 37: 0,
  43: 0,
  44: 99, 45: 0
};

/*
 * A base attack of 70 - 1.40 s by the measured curve - so there is room to move either way.
 *
 * Twelve seconds of hold, which is more than the measurement needs and exactly what it needs
 * if the answer is the unexpected one: should a hard strike LENGTHEN the attack, a full depth
 * could take byte 70 up towards 99, which is 10.7 s. A ramp still climbing when the note ends
 * reads as whatever fraction of it was visible, and that is the one error this run cannot
 * afford.
 */
var ATTACK_BASE = 70;
var RELEASE_BASE = 70;

/*
 * LONGER THAN THEY LOOK, AND THE GAP IS THE PART THAT MATTERS
 *
 * Run 6 could be tight because it asked which sample sounded, which a fraction of a second
 * answers. This one times two envelope stages, and both can run away from their base setting
 * in a direction nobody has measured yet - so the note has to outlast an attack that might
 * have been lengthened, and the gap has to outlast a release that might have been.
 *
 * The gap was 2 s and the release trace watches 90% of it. The next note therefore arrived
 * 0.2 s after the trace ended, the alignment error ate most of that, and one clip caught the
 * following strike in its last frames - which is 20 dB above anything in a release and became
 * the level everything else was measured against. The same release read 22 usable points in
 * one clip and 5 in its neighbour, entirely by whether the neighbour bled in.
 *
 * Eight seconds of gap on the release clips, then: a release of 70 is 1.4 s at its base and
 * the depth could stretch it several times over before the trace is in any danger. Fourteen
 * seconds of note on the attack clips, for the same reason in the other direction - if a hard
 * strike LENGTHENS the attack, a full depth could take byte 70 towards 99, which is 10.7 s,
 * and a ramp still climbing when the note ends reads as whatever fraction of it was visible.
 */
var TIMING = {
  hold: 14.0,
  gap: 8.0,
  sectionGap: 10.0,
  lead: 1.0,
  channel: 0
};

var TESTS = [];
var KEYGROUPS = [];
var nextKey = 36;

/// One keygroup, played at a list of velocities - the clips share it, as in run 6.
function sweep(spec) {
  var key = nextKey++;
  var set = {};
  Object.keys(BASE).forEach(function (k) { set[k] = BASE[k]; });
  Object.keys(spec.set).forEach(function (k) { set[k] = spec.set[k]; });

  spec.velocities.forEach(function (velocity) {
    TESTS.push({
      section: spec.section, analysis: 'level', label: spec.label + ' at velocity ' + velocity,
      key: key, velocity: velocity, hold: spec.hold || TIMING.hold,
      gapAfter: spec.gapAfter || TIMING.gap,
      setting: velocity, rising: spec.rising === true, watch: 'level', why: spec.why
    });
  });

  KEYGROUPS.push({ low: key, high: key, set: set, why: spec.why, sample: 'NOISE' });
}

/*
 * 1. Velocity to attack at full depth, across the whole velocity range.
 *
 * Eight strikes on one keygroup. Whichever way the attack moves, this says by how much and
 * whether there is a velocity that leaves it where the byte alone would put it - the pivot
 * that velocity-to-filter turned out to have at 65 and that nobody thought to look for until
 * a measurement insisted on it.
 */
sweep({
  section: 'attack depth 99', label: 'vel->attack 99', rising: true,
  velocities: [1, 16, 32, 48, 64, 80, 96, 127],
  set: { 3: ATTACK_BASE, 9: 99 },
  why: 'which way a harder strike moves the attack, by how much, and about what pivot'
});

/*
 * 2. The same at the depths the library actually uses.
 *
 * 30 and 75 are two of the four clusters in the real disks. Two velocities each, the softest
 * and the hardest, which is all that is needed once section 1 has the shape: the question
 * here is only whether the byte scales the effect in a straight line.
 */
[30, 75].forEach(function (depth) {
  sweep({
    section: 'attack depth ' + depth, label: 'vel->attack ' + depth, rising: true,
    velocities: [1, 127],
    set: { 3: ATTACK_BASE, 9: depth },
    why: 'whether the depth byte scales the effect in a straight line'
  });
});

/*
 * 3. The control, and the run rests on it.
 *
 * A depth of zero must give the same attack at velocity 1 as at 127. If it does not then
 * something else in this programme is following the strike, and every number above is
 * measuring that instead.
 */
sweep({
  section: 'attack depth 0', label: 'vel->attack 0', rising: true,
  velocities: [1, 127],
  set: { 3: ATTACK_BASE, 9: 0 },
  why: 'the control: with no depth, velocity must change nothing'
});

/*
 * 4. Velocity to release, at the sign the library uses and at its mirror.
 *
 * Held only long enough to be sitting still at the sustain when the key comes up, then
 * watched through the gap: the release is the one stage that happens after the note is let
 * go, so the analysis traces from the key-up for these.
 *
 * -50 first because nineteen of the library's twenty are there. +50 to see whether the sign
 * simply mirrors it, and 0 as the same control as above.
 */
[-50, 50, 0].forEach(function (depth) {
  sweep({
    section: 'release ' + (depth > 0 ? '+' : '') + depth,
    label: 'vel->release ' + depth,
    velocities: [1, 127],

    /*
     * THE SAME LENGTH AS EVERY OTHER NOTE, AND A LONG PAUSE AFTER IT.
     *
     * These were three seconds, and the first take of this run came back with all six of
     * them sounding for fourteen - flat at full level, then stopping dead, which is a note
     * still held rather than a tail. Whatever did that, a plan that asks for one note length
     * in one section and a different one everywhere else is a plan with a way to go wrong
     * that a uniform one does not have. So they are fourteen seconds like the rest: if the
     * lengths are honoured this measures exactly what it did before, and if something is
     * imposing a single length on every note then it is already the length we asked for.
     *
     * The pause is the other half. At eleven seconds apart with fourteen seconds of sound,
     * consecutive release clips ran into each other and the analysis saw three notes where
     * six were played. Twenty seconds outlasts a release several times longer than the model
     * thinks this one is, which is the only honest amount to allow for something unmeasured.
     */
    hold: 14.0, gapAfter: 20.0,
    set: { 3: 0, 6: RELEASE_BASE, 10: depth & 0xFF },
    why: 'what the sign of a signed depth means, at the value the library chose'
  });
});

function schedule() {
  var events = [];
  var clips = [];
  var at = TIMING.lead;
  var section = null;

  /*
   * The gap belongs to the clip BEFORE it, not to the run.
   *
   * A release needs a long pause after it and an attack does not, and one global gap made
   * every note pay for the slowest. More than that, it is the previous note's tail that has
   * to fit in the gap, so the previous note is what should decide how long it is.
   */
  var previous = null;

  TESTS.forEach(function (c) {
    var first = c.section !== section;
    if (clips.length)
      at += first ? Math.max(TIMING.sectionGap, previous.gapAfter) : previous.gapAfter;
    section = c.section;
    previous = c;

    events.push({ at: at, kind: 'on', note: c.key, velocity: c.velocity });
    events.push({ at: at + c.hold, kind: 'off', note: c.key });

    clips.push({
      section: c.section, analysis: c.analysis, label: c.label, setting: c.setting,
      note: c.key, velocity: c.velocity, first: first, rising: c.rising, watch: c.watch,
      from: at, releasedAt: at + c.hold, hold: c.hold
    });

    at += c.hold;
  });

  return { events: events, clips: clips, seconds: at + TIMING.gap };
}

function keygroups() { return KEYGROUPS; }
function clips() { return schedule().clips; }

module.exports = {
  TESTS: TESTS, TIMING: TIMING, BASE: BASE, LOOPING: LOOPING,
  ATTACK_BASE: ATTACK_BASE, RELEASE_BASE: RELEASE_BASE,
  FROM: 99, OPEN_FROM: 99, CLOSE_FROM: 99, RELEASE_FROM: 99, AMOUNT: 0,
  schedule: schedule, keygroups: keygroups, clips: clips
};
